### ISSUE TITLE
Add matmul op

### ISSUE THREAD

**Issue by Adnios** [kaixih/cudnn_frontend_test#2]
Thanks @kaixih .

I am currently attempting to benchmark the gemm and conv operations of cudnn. This repository has been incredibly helpful in saving me time. Additionally, I have added a matmul operation based on your previous implementation. If possible, I would like to submit a pull request to this repository.

https://github.com/Adnios/cudnn_frontend_test

**Comment by kaixih** [comment]
I am glad this helps in your case.

Yes, please submit a PR of your changes. Thanks.
